language: minimal
sudo: required
services:
  - docker
before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
jobs:
  include:
    - stage: Download Market Data
      script: ./build/get-market-data.sh
    - stage: Optimize Strategies
      script: ./build/optimize-strategies.sh -e 100 -d "$TRAVIS_BUILD_DIR/user_data/strategies"
