language: minimal
sudo: required
services:
  - docker
before_install:
- sudo apt-get install jq
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
jobs:
  include:
    - stage: Build
      script: 
        - travis_wait 90 ./build/build.sh -e 65 -d "$TRAVIS_BUILD_DIR" -t "$GithubToken"
