language: minimal
sudo: required
services:
  - docker
before_install:
- sudo apt-get install jq
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
jobs:
  include:
    - stage: Build
      script: ./build/get-market-data.sh -e 10 -d "$TRAVIS_BUILD_DIR/user_data/strategies"
