language: csharp
sudo: required
mono: none
dotnet: 3.1
dist: xenial
script:
  - dotnet restore
  - dotnet build
  - dotnet test ./FrostAura.Services.Plutus.Core.Tests/
  - dotnet test ./FrostAura.Services.Plutus.Data.Tests/